Feature/frontend adjustments
gecid-aia/turkers-chat pull request #14
Opened 2020-02-27 01:15 UTC by lucianoratamero

![image](https://user-images.githubusercontent.com/1103672/75403084-6399cb80-58e5-11ea-9d76-98d59825df75.png)
![image](https://user-images.githubusercontent.com/1103672/75403117-7f04d680-58e5-11ea-8176-abd7e0b3c66c.png)
![image](https://user-images.githubusercontent.com/1103672/75403138-8deb8900-58e5-11ea-9192-fe09140036d9.png)

2020-02-27 15:46 UTC, berinhard requested changes
@lucianoratamero vou deployar pra galera fazer os testes mas tive só um problema. como turker, ao selecionar uma mesagem para responder o input com o reply_to aparece em todos os chats, ao invés de somente no que está ativo. tipo esse print aqui:

![Screenshot from 2020-02-27 12-42-12](https://user-images.githubusercontent.com/238223/75459728-25d98900-595f-11ea-8136-21f8cd5cb9c4.png)

2020-03-02 18:48 UTC, berinhard commented
@lucianoratamero chegou a olhar esse review?

2020-03-02 18:49 UTC, lucianoratamero commented
eita @berinhard , tinha visto não! vou ver que que houve mais tarde

2020-03-02 19:56 UTC, lucianoratamero commented
@berinhard pode checar de novo? acabei de fazer um patch meio grosseiro aqui, mas que resolve.
![fix](https://user-images.githubusercontent.com/1103672/75712455-b6d59a80-5ca6-11ea-9752-b1bd866b5bff.gif)

2020-03-02 20:46 UTC, berinhard approved these changes
LINDIU <3

2020-03-02 20:46 UTC, merged